### ISSUE TITLE
Fix: Ajuste de Layout responsivo

### ISSUE THREAD

**Issue by Allyhere** [pythonbrasil/pybr2024-site#9]
## Objetivo

Solucionar os problemas de acessibilidade da landing page:

**Header passa a ser oculto até 1071px**
O container da imagem não causa overflow porém não se reajusta.
![Header com a logo do PYBR2024 e os dizeres PELA COMUNDADE PARA COMUNDADE  com as palavras separadas entre si por estrelas](https://github.com/user-attachments/assets/6c3c441c-ca84-4019-a824-07e7ce2fbf3e)

**Links de patrocinadores estão truncados até 751px**
Links não estão reajustando de forma responsiva.
| View | Box view |
| --- | --- |
| ![3 links da sessão de de navegação que entrando dentro uns dos outros](https://github.com/user-attachments/assets/2f75870d-d3ee-481d-9b73-2ea20003d85a) | ![image](https://github.com/user-attachments/assets/6960de0c-7d7b-4c0b-8891-ead32cba4290) |

**Sessão de patrocinadores causa overflow até aproximadamente 450px**
| View | Box view |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/9cbc2392-3b42-4e95-825d-3e04c8c5b60e) | ![image](https://github.com/user-attachments/assets/c11a4d8c-1924-42bd-9ee2-94e379b23f96) |

**Ícones não se reajustam até 360px**
| View | Box view |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/6870c13d-f698-44a6-90cd-dff172e3b3f1) | ![image](https://github.com/user-attachments/assets/4002b88b-0c9e-43d9-8c0d-6e2b34684642) |

**Excesso de nodes no HTML pode prejudicar a robustez da responsividade**

| Full View | HTML View |
| --- | --- |
| <image src="https://github.com/user-attachments/assets/32af8f94-6f1e-45b9-ab0e-8fe5c280404b" width="400" /> | ![image](https://github.com/user-attachments/assets/edab88e8-55d5-4e15-9e8f-94fb4603115c) |

Closes #8

**Comment by biancarosa** [comment]
Muito bom!

Uma cola de como deveria ser o layout responsivo do site: 

Algumas seções a gente ainda não implementou, e acho que isso sai do escopo dessa issue, mas ajeitar as existentes usando como base essa descrição + esse layout é um excelente escopo.

![site v1](https://github.com/user-attachments/assets/1c2063e3-d893-49f9-911b-6b014b5ba1eb)

**Comment by Allyhere** [comment]
@biancarosa obrigado! Acredito que o ajuste do footer possa ser baseado nisso, por exemplo. O ideal seria que todos os elementos textuais estivessem como texto, como os títulos "Patrocínio" ou a parte das datas do banner do evento, você acha que seria possível?
